FROM node:16-alpine as builder

WORKDIR /WWW/WWWROOT/

ADD package.json /WWW/WWWROOT/
RUN npm i --registry https://registry.npm.taobao.org

ADD . /WWW/WWWROOT/

RUN npm run build

FROM nginx:alpine

COPY --from=builder WWW/WWWROOT/dist/ /usr/share/nginx/html/
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf


# 构建指令
# docker build -f Dockerfile.prod -t vue3 .

# 启动容器
# docker run -p 4000:80 -it --name web vue3